name: Create announcements
on:
  schedule:
    # Schedule to run every 30 minutes (at odd times to balance server load)
    - cron: '10,40 * * * *'
  # run on request (via button in actions menu)
  workflow_dispatch:

jobs:
  deploy:
    name: Generate announcement
    runs-on: ubuntu-latest

    permissions:
      # Give default GITHUB_TOKEN write permission to commit and push the changed files back to repo.
      contents: write
      
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup r2u
        uses: eddelbuettel/github-actions/r2u-setup@master
        
      - name: Package Dependencies

        run: Rscript -e 'install.packages(c("googlesheets4", "httr", "digest"))'

      - name: Create announcements
        run: |
          Rscript create_announcements.R

      - name: Commit and Push Results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update announcements" -a || echo "No changes to commit"
          git push

      - name: Trigger Publish Workflow
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'publish-trigger',
            });
