name: Create announcements
on:
  # run on any push
  schedule:
    # Schedule to run every hour
    - cron: '0 */1 * * *'

  # run on request (via button in actions menu)
  workflow_dispatch:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  deploy:
    name: Generate announcement
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: eddelbuettel/github-actions/r-ci-setup@master

      - name: Push to shiny.io
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e "install.packages(c('googlesheets4', 'httr', 'digest')"
          Rscript create_announcements.R

    - name: Commit and Push Results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update announcements" -a || echo "No changes to commit"
        git push

    - name: Trigger Publish Workflow
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: 'publish-trigger',
          });
