name: Create announcements
on:
  schedule:
    # Schedule to run every hour
    - cron: '10,25,40,55 * * * *'
  # run on request (via button in actions menu)
  workflow_dispatch:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  deploy:
    name: Generate announcement
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
            r-version: '3.5.3'

      - name: Package Dependencies
        run: Rscript -e 'install.packages(c("googlesheets4", "httr", "digest"))'

      - name: Create announcements
        run: |
          Rscript create_announcements.R

      - name: Commit and Push Results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update announcements" -a || echo "No changes to commit"
          git push

      - name: Trigger Publish Workflow
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'publish-trigger',
            });
